CC = gcc
CFLAGS = -Wall

all: server client

server: server.o
	$(CC) -o server server.o

server.o: server.c
	$(CC) $(CFLAGS) -c server.c

client: client.o
	$(CC) -o client client.o

client.o: client.c
	$(CC) $(CFLAGS) -c client.c

clean:
	rm -f *.o server client
